name: 'NPM Custom Action'
description: 'Installing and caching NPM'
inputs:
  path-of-folder:  # id of input
    description: 'the path to cache'
    required: true
runs:
  using: "composite"
  steps:
      - name: Cache NPM Dependencies
        uses: actions/cache@v4
        with:
            path: ${{ inputs.path-of-folder }}
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}    

      - name: Install Dependency and Unit Testing
        run: npm install
        shell: bash